version: '3'

services:
  nginx-rtmp:
    image: alfg/nginx-rtmp
    restart: unless-stopped
    ports:
      - 1935:1935
      - 80:80
      - 443:443
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ./certs:/opt/certs
      - ./nginx.conf:/etc/nginx/nginx.conf.template
      - ./recordings:/recordings
